FROM ashesfall/iwfm-base:1403-php7.4-apache

WORKDIR /

COPY model/Simulation/Groundwater/C2VSimFG_Groundwater1974.dat /Simulation/Groundwater/C2VSimFG_Groundwater1974.dat

ENTRYPOINT /run_simulation.sh