FROM ashesfall/iwfm-airflow:latest

COPY runner/airflow_agent.sh /airflow_agent.sh

USER root
RUN chmod o+w /
RUN mkdir /data
RUN chown airflow /data

USER airflow

ENV WORKING_PATH=/data
ENTRYPOINT /airflow_agent.sh