FROM tjhatch/iwfm-manager:latest

USER root
RUN pip install "PyAthena>1.2.0"
RUN pip install awswrangler
RUN pip install geojson-to-sqlite
RUN pip install apache-superset
RUN mkdir /backups ; chmod 777 /backups

# RUN echo "PREVENT_UNSAFE_DB_CONNECTIONS = False" >> /app/superset/config.py

# USER superset
COPY runner/dashboard_backup.py /dashboard_backup.py
COPY runner/dashboard_download.py /dashboard_download.py
COPY runner/superset.sh /superset.sh

ENTRYPOINT /init.sh