FROM ashesfall/iwfm-base:1403-ubuntu20.04

WORKDIR /

COPY model/Simulation/Groundwater/C2VSimFG_Groundwater1974.dat /Simulation/Groundwater/C2VSimFG_Groundwater1974.dat

ENTRYPOINT /run_simulation.sh