FROM apache/superset

USER root
RUN apt-get install -y sqlite3 libsqlite3-dev
RUN apt-get install -y sudo

RUN pip3 install awswrangler

RUN mkdir /backups ; chmod 777 /backups
RUN echo "PREVENT_UNSAFE_DB_CONNECTIONS = False" >> /app/superset/config.py

USER superset
COPY runner/dashboard_backup.py /dashboard_backup.py
COPY runner/dashboard_download.py /dashboard_download.py
COPY runner/superset.sh /superset.sh

ENTRYPOINT /superset.sh