      SUBROUTINE SETMAXERROR (MAXERR)
C
      COMMON /ZSTATUS/ TOTAL_NUMB,  CURRENT_NUMB,
     *                 INTERRUPT, NERROR, MAXERROR
      INTEGER TOTAL_NUMB, CURRENT_NUMB, INTERRUPT
      INTEGER NERROR, MAXERROR
C
      MAXERROR = MAXERR
C
      RETURN
      END
