        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:29 2020
        MODULE CLN1BDADJ__genmod
          INTERFACE 
            SUBROUTINE CLN1BDADJ(KSTP,KPER)
              INTEGER(KIND=4) :: KSTP
              INTEGER(KIND=4) :: KPER
            END SUBROUTINE CLN1BDADJ
          END INTERFACE 
        END MODULE CLN1BDADJ__genmod
