        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:21 2020
        MODULE CONCCONV__genmod
          INTERFACE 
            SUBROUTINE CONCCONV(ICOMP,ITITER,ICNVG)
              INTEGER(KIND=4) :: ICOMP
              INTEGER(KIND=4) :: ITITER
              INTEGER(KIND=4) :: ICNVG
            END SUBROUTINE CONCCONV
          END INTERFACE 
        END MODULE CONCCONV__genmod
