        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:27 2020
        MODULE GLO2SMS1UR__genmod
          INTERFACE 
            SUBROUTINE GLO2SMS1UR(KITER)
              INTEGER(KIND=4) :: KITER
            END SUBROUTINE GLO2SMS1UR
          END INTERFACE 
        END MODULE GLO2SMS1UR__genmod
