        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:18 2020
        MODULE GNCN2DISU1DA__genmod
          INTERFACE 
            SUBROUTINE GNCN2DISU1DA
            END SUBROUTINE GNCN2DISU1DA
          END INTERFACE 
        END MODULE GNCN2DISU1DA__genmod
