      SUBROUTINE DSSCLEARSTATUS ()
C	
C
      COMMON /ZSTATUS/ TOTAL_NUMB,  CURRENT_NUMB,
     *                 INTERRUPT, NERROR, MAXERROR
      INTEGER TOTAL_NUMB, CURRENT_NUMB, INTERRUPT
      INTEGER NERROR, MAXERROR
C
      TOTAL_NUMB = 0
      CURRENT_NUMB = 0
      INTERRUPT = 0
      NERROR = 0
C
      RETURN
      END
