        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:31 2020
        MODULE CHANNELAREA__genmod
          INTERFACE 
            SUBROUTINE CHANNELAREA(ISTSG,L)
              INTEGER(KIND=4) :: ISTSG
              INTEGER(KIND=4) :: L
            END SUBROUTINE CHANNELAREA
          END INTERFACE 
        END MODULE CHANNELAREA__genmod
