        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:34 2020
        MODULE FIRST_ACTIVE_BELOW2__genmod
          INTERFACE 
            SUBROUTINE FIRST_ACTIVE_BELOW2(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE FIRST_ACTIVE_BELOW2
          END INTERFACE 
        END MODULE FIRST_ACTIVE_BELOW2__genmod
