        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:18 2020
        MODULE ADDIAJA_GNCN__genmod
          INTERFACE 
            SUBROUTINE ADDIAJA_GNCN(SMAT)
              USE SPARSEMODULE
              TYPE (SPARSEMATRIX) :: SMAT
            END SUBROUTINE ADDIAJA_GNCN
          END INTERFACE 
        END MODULE ADDIAJA_GNCN__genmod
