        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:17 2020
        MODULE ATS1DPFCT__genmod
          INTERFACE 
            SUBROUTINE ATS1DPFCT
            END SUBROUTINE ATS1DPFCT
          END INTERFACE 
        END MODULE ATS1DPFCT__genmod
