        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:32 2020
        MODULE CLEAR_MODFLOW_MEMORY__genmod
          INTERFACE 
            SUBROUTINE CLEAR_MODFLOW_MEMORY
            END SUBROUTINE CLEAR_MODFLOW_MEMORY
          END INTERFACE 
        END MODULE CLEAR_MODFLOW_MEMORY__genmod
