        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:29 2020
        MODULE CLN1BDWR__genmod
          INTERFACE 
            SUBROUTINE CLN1BDWR(KSTP,KPER)
              INTEGER(KIND=4) :: KSTP
              INTEGER(KIND=4) :: KPER
            END SUBROUTINE CLN1BDWR
          END INTERFACE 
        END MODULE CLN1BDWR__genmod
