        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:23 2020
        MODULE DDF1AD__genmod
          INTERFACE 
            SUBROUTINE DDF1AD(IUDDF)
              INTEGER(KIND=4) :: IUDDF
            END SUBROUTINE DDF1AD
          END INTERFACE 
        END MODULE DDF1AD__genmod
