        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:23 2020
        MODULE DDF1FM__genmod
          INTERFACE 
            SUBROUTINE DDF1FM(KSTP,KPER)
              INTEGER(KIND=4) :: KSTP
              INTEGER(KIND=4) :: KPER
            END SUBROUTINE DDF1FM
          END INTERFACE 
        END MODULE DDF1FM__genmod
