        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:23 2020
        MODULE DDF1BD__genmod
          INTERFACE 
            SUBROUTINE DDF1BD(KSTP,KPER)
              INTEGER(KIND=4) :: KSTP
              INTEGER(KIND=4) :: KPER
            END SUBROUTINE DDF1BD
          END INTERFACE 
        END MODULE DDF1BD__genmod
