        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:29 2020
        MODULE FILLIDXGLO_CLN__genmod
          INTERFACE 
            SUBROUTINE FILLIDXGLO_CLN
            END SUBROUTINE FILLIDXGLO_CLN
          END INTERFACE 
        END MODULE FILLIDXGLO_CLN__genmod
