        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:23 2020
        MODULE FIRST_ACTIVE_BELOW__genmod
          INTERFACE 
            SUBROUTINE FIRST_ACTIVE_BELOW(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE FIRST_ACTIVE_BELOW
          END INTERFACE 
        END MODULE FIRST_ACTIVE_BELOW__genmod
