        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:24 2020
        MODULE GLO2SGBU1BD__genmod
          INTERFACE 
            SUBROUTINE GLO2SGBU1BD(KSTP,KPER)
              INTEGER(KIND=4) :: KSTP
              INTEGER(KIND=4) :: KPER
            END SUBROUTINE GLO2SGBU1BD
          END INTERFACE 
        END MODULE GLO2SGBU1BD__genmod
