        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:27 2020
        MODULE GLO2SMS1AP__genmod
          INTERFACE 
            SUBROUTINE GLO2SMS1AP(IOUT,KITER,ICNVG,KSTP,KPER)
              INTEGER(KIND=4) :: IOUT
              INTEGER(KIND=4) :: KITER
              INTEGER(KIND=4) :: ICNVG
              INTEGER(KIND=4) :: KSTP
              INTEGER(KIND=4) :: KPER
            END SUBROUTINE GLO2SMS1AP
          END INTERFACE 
        END MODULE GLO2SMS1AP__genmod
