        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:24 2020
        MODULE GLO2SGBU1RP__genmod
          INTERFACE 
            SUBROUTINE GLO2SGBU1RP(IN)
              INTEGER(KIND=4) :: IN
            END SUBROUTINE GLO2SGBU1RP
          END INTERFACE 
        END MODULE GLO2SGBU1RP__genmod
