        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:24 2020
        MODULE GLO2SGBU1AR__genmod
          INTERFACE 
            SUBROUTINE GLO2SGBU1AR(IN)
              INTEGER(KIND=4) :: IN
            END SUBROUTINE GLO2SGBU1AR
          END INTERFACE 
        END MODULE GLO2SGBU1AR__genmod
