        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:18 2020
        MODULE GNCN2DISU1AR__genmod
          INTERFACE 
            SUBROUTINE GNCN2DISU1AR(IUGNCN)
              INTEGER(KIND=4) :: IUGNCN
            END SUBROUTINE GNCN2DISU1AR
          END INTERFACE 
        END MODULE GNCN2DISU1AR__genmod
