        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:29 2020
        MODULE GRADTERMP__genmod
          INTERFACE 
            SUBROUTINE GRADTERMP
            END SUBROUTINE GRADTERMP
          END INTERFACE 
        END MODULE GRADTERMP__genmod
