        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:29:20 2020
        MODULE GWF2BAS7AD__genmod
          INTERFACE 
            SUBROUTINE GWF2BAS7AD(KPER,KSTP)
              INTEGER(KIND=4) :: KPER
              INTEGER(KIND=4) :: KSTP
            END SUBROUTINE GWF2BAS7AD
          END INTERFACE 
        END MODULE GWF2BAS7AD__genmod
