#ifndef __HECLIB_INCLUDED__
#define __HECLIB_INCLUDED__

#ifdef __cplusplus
extern "C" {
#endif

#if defined(_MSC_VER)
	typedef __int32 int32_t;
	typedef __int64 int64_t;
        #ifdef _WIN64
                typedef int64_t slen_t;
        #else
                typedef int32_t slen_t;
        #endif
#else
	#include <stdint.h>
        typedef int32_t slen_t;
#endif

/*------------------*/  
/* Fortran routines */  
/*------------------*/  
void      abort_(void);
void      addcentury_(int32_t *iyear);
void      anread_(int32_t *iunit, char *cpromp, int32_t *npromp, char *cline, int32_t *nline, slen_t _cpromp_len, slen_t _cline_len);
void      anrout_(int32_t *iounit);
void      asctrl_(int32_t *iunit, char *cfun, int32_t *iarg1, int32_t *iarg2, slen_t _cfun_len);
void      attach_(int32_t *iunit, char *ckywrd, char *cdfalt, char *contrl, char *cname, int32_t *istat, slen_t _ckywrd_len, slen_t _cdfalt_len, slen_t _contrl_len, slen_t _cname_len);
void      attcrk_(char *cleft, char *cright, int32_t *jks, int32_t *ks, int32_t *istat, slen_t _cleft_len, slen_t _cright_len);
void      attdcd_(char *contrl, char *cstat, int32_t *nbit, char *caccs, int32_t *nlen, char *ctype, char *cform, char *cmode, char *cprmp, char *cnop, int32_t *istdot, slen_t _contrl_len, slen_t _cstat_len, slen_t _caccs_len, slen_t _ctype_len, slen_t _cform_len, slen_t _cmode_len, slen_t _cprmp_len, slen_t _cnop_len);
void      attend_(void);
void      attmat_(char *ckyary, char *ckywrd, int32_t *ien, int32_t *jks, int32_t *ks, int32_t *jsub, slen_t _ckyary_len, slen_t _ckywrd_len);
void      attopn_(int32_t *iunit, char *ckywrd, char *cname, int32_t *istdin, int32_t *istdot, char *cstat, int32_t *nbit, char *caccs, int32_t *nlen, char *ctype, char *cform, char *cmode, int32_t *linac, int32_t *ldfalt, int32_t *istat, slen_t _ckywrd_len, slen_t _cname_len, slen_t _cstat_len, slen_t _caccs_len, slen_t _ctype_len, slen_t _cform_len, slen_t _cmode_len);
void      attset_(char *clin, slen_t _clin_len);
void      attsub_(char *cdfalt, char *cdfsub, int32_t *ndfalt, slen_t _cdfalt_len, slen_t _cdfsub_len);
void      bits_(int32_t *iarray, int32_t *ibitno, int32_t *iset, int32_t *lget);
void      bkdatw_(void);
void      cdate_(char *carray, slen_t _carray_len);
void      cdelet_(char *cname, int32_t *ierr, slen_t _cname_len);
void      ch2hol_(char *chr, int32_t *ihol, int32_t *nwords, slen_t _chr_len);
void      chdlm_(int32_t *itype, char *cstrng, int32_t *ibeg, int32_t *numb, int32_t *itbl, slen_t _cstrng_len);
void      chgtyp_(float *r1, float *r2);
void      chrblk_(char *cstr, slen_t _cstr_len);
void      chrfil_(char *cline, char *chr, slen_t _cline_len, slen_t _chr_len);
void      chrfl1_(void);
void      chrflb_(char *cstring, int32_t *ibeg, int32_t *iend, slen_t _cstring_len);
void      chrhol_(char *c, int32_t *is, int32_t *nc, int32_t *ic, int32_t *js, slen_t _c_len);
void      chrint_(int32_t *numb, char *cstring, slen_t _cstring_len);
void      chrlnb_(char *cline, int32_t *ilast, slen_t _cline_len);
void      chrwt1_(char *cstr, int32_t *nstr, slen_t _cstr_len);
void      chrwt_(int32_t *klfn, char *cstr, int32_t *nstr, slen_t _cstr_len);
void      cjchr_(char *cline, slen_t _cline_len);
void      cjstr_(char *cstr1, int32_t *nbeg1, int32_t *nlen1, char *cstr2, int32_t *nbeg2, slen_t _cstr1_len, slen_t _cstr2_len);
void      ckansi_(int32_t *iunit, int32_t *lansi);
void      clines_(int32_t *nlines);
void      clktime_(char *carray, slen_t _carray_len);
void      cparms_(char *cline, int32_t *nchs, slen_t _cline_len);
void      crenam_(char *coldnm, char *cnewnm, int32_t *ierr, slen_t _coldnm_len, slen_t _cnewnm_len);
void      ctime_(char *carray, slen_t _carray_len);
void      curtim_(int32_t *jul, int32_t *min);
void      datcll_(int32_t *julin, int32_t *intime, int32_t *julout, int32_t *ioutim);
void      datcln_(int32_t *julin, int32_t *intime, int32_t *julout, int32_t *ioutim);
void      datime_(int32_t *jyr, int32_t *nday, int32_t *j10sec);
void      datjul_(char *cdate, int32_t *jul, int32_t *ierr, slen_t _cdate_len);
void      datymd_(char *cdate, int32_t *iyr, int32_t *imon, int32_t *iday, int32_t *ierr, slen_t _cdate_len);
void      dcdltr_(float *r1, int32_t *nr1, int32_t *iprec, float *base, int32_t *lbase, int32_t *icmval, int32_t *ncmval, int32_t *kcmval, int32_t *ibbyte, int32_t *isize, int32_t *istat);
void      dcinfo_(int32_t *ih, int32_t *nh, int32_t *ibgelm, int32_t *nelms, int32_t *istwrd, int32_t *nwords, int32_t *ibbyte);
void      dcreal_(float *r, int32_t *nr, int32_t *iskm, float *base, int32_t *lbase, int32_t *isize, int32_t *iprec, int32_t *icmval, int32_t *ncmval, int32_t *kcmval, int32_t *ih, int32_t *nh, int32_t *kh, int32_t *istat);
void      dcrept_(float *r1, int32_t *nr1, float *r2, int32_t *nr2, int32_t *i1, int32_t *ni1, int32_t *ki1, int32_t *istat);
void      dcsd3r_(float *r1, int32_t *nr1, int32_t *icmval, int32_t *ncmval, int32_t *kcmval, int32_t *ibbyte, int32_t *istat);
void      dhchek_(int32_t *istbyt, int32_t *ih, int32_t *nh, int32_t *istat);
void      dhinfo_(int32_t *ih, int32_t *nh, int32_t *iskm, int32_t *nr2, float *base, int32_t *lbase, int32_t *nelms, int32_t *isize, int32_t *iprec, int32_t *lrpeat, int32_t *ldelta, int32_t *lsigdt, int32_t *istat);
void      dhinit_(float *base, int32_t *ibase, int32_t *nbase, int32_t *ih, int32_t *nh, int32_t *iprec, int32_t *isize, int32_t *iskm, int32_t *nbits, int32_t *nbytes, int32_t *nelms, int32_t *istat, int32_t *lbase, int32_t *ldelta, int32_t *lsigdt);
void      dibin_(int32_t *iunit, int32_t *numb);
void      dmreal_(float *r, int32_t *ibgelm, int32_t *nelms, int32_t *icmval, int32_t *ncmval, int32_t *kcmval, int32_t *ih, int32_t *nh, int32_t *istat, int32_t *iskm);
void      dudltr_(float *r1, int32_t *nr1, int32_t *iprec, float *base, int32_t *lbase, int32_t *icmval, int32_t *ncmval, int32_t *ibbyte, int32_t *isize, int32_t *istat);
void      dureal_(float *r, int32_t *kr, int32_t *ibgelm, int32_t *nelms, int32_t *icmval, int32_t *ncmval, int32_t *kcmval, int32_t *ih, int32_t *nh, int32_t *istat);
void      durept_(float *r1, int32_t *nr1, float *r2, int32_t *nr2, int32_t *i1, int32_t *ni1, int32_t *istat);
void      dusd3r_(float *r1, int32_t *nr1, int32_t *icmval, int32_t *ncmval, int32_t *ibbyte, int32_t *istat);
void      findlm_(char *ca, int32_t *ka, int32_t *na, int32_t *nf, int32_t *ibf, int32_t *ilf, int32_t *idt, int32_t *idp, int32_t *itbl, slen_t _ca_len);
int       fortranclose_(int32_t *iunit);
void      fortranflush_(int32_t *iunit);
int       fortranopen_(int32_t *iunit, char *filename, slen_t _filename_len);
int       fortranwrite_(int32_t *iunit, char *string, int32_t *ladv, slen_t _string_len);
void      getbin_(int32_t *jwords, int32_t *nbytes, char *crepr, slen_t _crepr_len);
void      gethol_(int32_t *istr, int32_t *ipos, int32_t *ich);
void      getime_(char *cin, int32_t *ibline, int32_t *lenlin, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *istat, slen_t _cin_len);
void      getnam_(int32_t *ilfn, char *cname, int32_t *iflag, slen_t _cname_len);
void      gnumrg_(char *cname, int32_t *nrange, int32_t *nvalue, int32_t *istat, slen_t _cname_len);
void      gstrrg_(char *cname, char *cstr, int32_t *nstr, int32_t *istat, slen_t _cname_len, slen_t _cstr_len);
void      gtcopt_(char *cline, char *copt, int32_t *nchrs, slen_t _cline_len, slen_t _copt_len);
void      hol2ch_(int32_t *ihol, char *chr, int32_t *nwords, slen_t _chr_len);
void      holchr_(int32_t *ic, int32_t *is, int32_t *nc, char *c, int32_t *js, slen_t _c_len);
int64_t i4toi8_(int32_t *i4);
int       i8toi4_(int64_t *i8);
int       ibits_(int32_t *iw, int32_t *ibit, int32_t *nbits);
int       icentury_(void);
int       ictime_(int32_t *jul1, int32_t *itime1, int32_t *jul2, int32_t *itime2);
int       idaywk_(int32_t *jul);
int       ihm2m_(char *ctime, slen_t _ctime_len);
int       ihms2s_(char *ctime, slen_t _ctime_len);
int       inctim_(int32_t *interval, int32_t *mindayflag, int32_t *nperiods, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime);
int       indexr_(char *cstr1, char *cstr2, slen_t _cstr1_len, slen_t _cstr2_len);
int       intchr_(char *cstring, slen_t _cstring_len);
int       intgr_(char *cline, int32_t *nbeg, int32_t *nlen, int32_t *ierr, slen_t _cline_len);
void      intgrc_(int32_t *numb, char *cline, int32_t *nbeg, int32_t *nlen, slen_t _cline_len);
int       iscan_(char *cstr1, int32_t *nbeg1, int32_t *nlen1, char *cstr2, int32_t *nbeg2, int32_t *nlen2, int32_t *ipos2, slen_t _cstr1_len, slen_t _cstr2_len);
int       iymdjl_(int32_t *iyr, int32_t *imon, int32_t *iday);
int       jliymd_(int32_t *jul, int32_t *iyr, int32_t *imon, int32_t *iday);
void      juldat_(int32_t *jul, int32_t *istyle, char *cdate, int32_t *ndate, slen_t _cdate_len);
int       lbtest_(int32_t *iw, int32_t *ibit);
int       lcompar_(float *svalues, float *dvalues, int32_t *ipos, int32_t *ldouble, float *val);
int       lcopts_(char *copts, char *chr, slen_t _copts_len, slen_t _chr_len);
int       leqner_(float *x, float *y, float *tol);
int       leqnerd_(double *x, double *y, float *tol);
void      lflnb_(char *cline, int32_t *nbeg, int32_t *nlen, int32_t *ibegnb, int32_t *ilennb, slen_t _cline_len);
int       lgener_(float *x, float *y, float *tol);
int       lgtner_(float *x, float *y, float *tol);
int       lisfil_(char *str, slen_t _str_len);
int       lisnum_(char *cstrng, slen_t _cstrng_len);
void      ljchr_(char *cline, int32_t *nline, slen_t _cline_len);
void      ljstr_(char *cstr1, int32_t *nbeg1, int32_t *nlen1, char *cstr2, int32_t *nbeg2, slen_t _cstr1_len, slen_t _cstr2_len);
int       llener_(float *x, float *y, float *tol);
int       lltner_(float *x, float *y, float *tol);
void      locase_(char *cline, slen_t _cline_len);
int       lpopt_(char *copt, slen_t _copt_len);
int       m2ihm_(int32_t *min, char *ctime, slen_t _ctime_len);
void      match_(char *cstr, int32_t *ibeg, int32_t *ilen, char *clist, int32_t *nlist, int32_t *nlen, int32_t *imatch, slen_t _cstr_len, slen_t _clist_len);
int       messag_(int32_t *iunit, int32_t *iout, char *cname, slen_t _cname_len);
void      mvbits_(int32_t *iw, int32_t *ib, int32_t *nb, int32_t *jw, int32_t *jb);
void      namfil_(int32_t *ifn, char *cnames, int32_t *inames, int32_t *max, int32_t *istat, slen_t _cnames_len);
void      namlst_(char *cnames, int32_t *inames, slen_t _cnames_len);
int       nindx_(char *cstr1, char *cstr2, slen_t _cstr1_len, slen_t _cstr2_len);
int       nindxr_(char *cstr1, char *cstr2, slen_t _cstr1_len, slen_t _cstr2_len);
int       nopers_(int32_t *interval, int32_t *mindayflag, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime);
int       nscan_(char *cstr1, int32_t *nbeg1, int32_t *nlen1, char *cstr2, int32_t *nbeg2, int32_t *nlen2, slen_t _cstr1_len, slen_t _cstr2_len);
void      nserch_(char *cnam, int32_t *loc, char *cnames, int32_t *inames, slen_t _cnam_len, slen_t _cnames_len);
int       numlin_(char *cfname, slen_t _cfname_len);
void      panred_(int32_t *iunit, char *cpromp, int32_t *npromp, char *cline, int32_t *nline, slen_t _cpromp_len, slen_t _cline_len);
void      parseq_(char *cline, int32_t *maxf, int32_t *nfield, char *clettr, int32_t *ibf, int32_t *ief, int32_t *ilf, slen_t _cline_len, slen_t _clettr_len);
void      parsli_(char *cline, int32_t *maxf, int32_t *nfield, int32_t *ibf, int32_t *ief, int32_t *ilf, slen_t _cline_len);
void      pattch_(int32_t *iunit, char *ckey, char *cdef, char *contrl, char *cstr, int32_t *istat, slen_t _ckey_len, slen_t _cdef_len, slen_t _contrl_len, slen_t _cstr_len);
void      pcdlin_(void);
void      pdisp_(char *op, char *copt, int32_t *up, slen_t _op_len, slen_t _copt_len);
void      pedit_(void);
void      pend_(void);
void      perr_(void);
void      pexlin_(void);
void      pfind_(int32_t *lfn, char *string, int32_t *line1, int32_t *up, int32_t *found, int32_t *idsp, slen_t _string_len);
void      pfnkey_(char *cnkey, char *cstrng, int32_t *ns, slen_t _cnkey_len, slen_t _cstrng_len);
void      pgfscn_(float *cfield, float *cfmt, int32_t *ival);
void      pgtlin_(int32_t *leof);
void      pinqir_(char *cinstr, char *cpram, int32_t *npram, slen_t _cinstr_len, slen_t _cpram_len);
void      pitab_(void);
void      pldfun_(int32_t *istat);
void      pldmac_(char *cname, int32_t *istat, slen_t _cname_len);
void      pldscn_(char *cscrn, slen_t _cscrn_len);
void      pmain_(int32_t *iscrt, char *clin1, char *clin2, int32_t *ientry, slen_t _clin1_len, slen_t _clin2_len);
void      pmcsub_(char *mastxt, char *partxt, int32_t *parcnt, int32_t *parstr, int32_t *parlen, char *subtxt, int32_t *subcnt, int32_t *substr, int32_t *sublen, slen_t _mastxt_len, slen_t _partxt_len, slen_t _subtxt_len);
void      pnxtln_(int32_t *k, int32_t *iss, int32_t *nl, int32_t *nlx, int32_t *ml, int32_t *mlx, char *clinx, int32_t *lend, slen_t _clinx_len);
void      posfl_(int32_t *iunit, int32_t *iline, int32_t *istat);
void      prdmen_(char *c, int32_t *i, slen_t _c_len);
void      pread1_(char *clin1, slen_t _clin1_len);
void      pread2_(char *clin1, char *clin2, slen_t _clin1_len, slen_t _clin2_len);
void      pread_(int32_t *iscrt);
void      preadc_(int32_t *iscrt, char *clin1, int32_t *ientry, void *return_1, slen_t _clin1_len);
void      prstat_(int32_t *lflag, char *chcom, char *chfunc, slen_t _chcom_len, slen_t _chfunc_len);
void      prtary_(float *array, int32_t *narray);
void      prtwrd_(int32_t *iaddr, int32_t *nwords, int32_t *lhead);
void      pscatt_(char *catt, char *cscn, int32_t *isatt, int32_t *iline, int32_t *nline, int32_t *iofset, int32_t *ipstat, slen_t _catt_len, slen_t _cscn_len);
void      pschin_(float *cline, int32_t *nnchr, int32_t *lmatch);
void      pset_(char *cinstr, char *cpram, int32_t *npram, slen_t _cinstr_len, slen_t _cpram_len);
void      psetfn_(char *cinkey, char *cstrng, int32_t *nstrng, slen_t _cinkey_len, slen_t _cstrng_len);
void      psfscn_(int32_t *ival);
void      pslmen_(char *c1, char *c2, int32_t *i, slen_t _c1_len, slen_t _c2_len);
void      pslscn_(int32_t *lresp);
void      pttach_(int32_t *iunit, char *ckey, char *cdef, char *contrl, char *cstr, int32_t *istat, slen_t _ckey_len, slen_t _cdef_len, slen_t _contrl_len, slen_t _cstr_len);
void      puthol_(int32_t *istr, int32_t *ipos, int32_t *ich);
void      r2sd3_(float *r, int32_t *i2);
void      rattim_(char *cstr, int32_t *nstr, int32_t *rtime, int32_t *istat, slen_t _cstr_len);
void      rbell_(void);
void      remblk_(char *cin, char *cout, int32_t *nout, slen_t _cin_len, slen_t _cout_len);
void      rjchr_(char *cline, slen_t _cline_len);
void      rjstr_(char *cstr1, int32_t *nbeg1, int32_t *nlen1, char *cstr2, int32_t *nbeg2, slen_t _cstr1_len, slen_t _cstr2_len);
void      scnchk_(char *c, int32_t *i, int32_t *l, slen_t _c_len);
void      sd32r_(int32_t *i2, float *r);
void      setdlm_(int32_t *itype, char *cstrng, int32_t *ibeg, int32_t *numb, int32_t *itbl, slen_t _cstrng_len);
void      setnam_(char *cpsudo, char *ctrue, int32_t *max, char *cnames, int32_t *inames, int32_t *ilistl, int32_t *istat, slen_t _cpsudo_len, slen_t _ctrue_len, slen_t _cnames_len);
void      snumrg_(char *cname, int32_t *nrange, int32_t *nvalue, int32_t *istat, slen_t _cname_len);
void      sstrrg_(char *cname, char *cstr, int32_t *nstr, int32_t *istat, slen_t _cname_len, slen_t _cstr_len);
void      stdinc_(char *cwait, char *cecho, char *cbreak, char *cflush, int32_t *iascii, int32_t *icode, slen_t _cwait_len, slen_t _cecho_len, slen_t _cbreak_len, slen_t _cflush_len);
void      stuffuserheader_(char *label, char *item, float *ruhead, int32_t *kuhead, int32_t *nuhead, int32_t *istat, slen_t _label_len, slen_t _item_len);
void      subdat_(char *cline, slen_t _cline_len);
void      tempname_(char *cname, int32_t *iunit, slen_t _cname_len);
void      trunam_(char *cpsudo, char *ctru, char *cnames, int32_t *inames, slen_t _cpsudo_len, slen_t _ctru_len, slen_t _cnames_len);
void      txtcol_(char *cfgin, char *cbgin, char *cattin, slen_t _cfgin_len, slen_t _cbgin_len, slen_t _cattin_len);
void      unstuffuserheader_(char *label, char *item, int32_t *ipos, float *ruhead, int32_t *nuhead, int32_t *istat, slen_t _label_len, slen_t _item_len);
void      upcase_(char *cline, slen_t _cline_len);
void      vansi_(int32_t *idsp);
void      vatt_(int32_t *iatt);
void      vend_(void);
void      verase_(void);
void      verasg_(void);
void      vinit_(int32_t *jdsp);
void      vmovcr_(int32_t *irp, int32_t *icp);
void      vset_(char *cmode, char *cspec, slen_t _cmode_len, slen_t _cspec_len);
void      vwtla_(char *cl, int32_t *iatt, int32_t *irow, int32_t *icol, slen_t _cl_len);
void      wait_(int32_t *i1, int32_t *i2, int32_t *i3);
void      when_(char *cdat, char *ctim, slen_t _cdat_len, slen_t _ctim_len);
void      wind_(int32_t *ilfn);
void      xqtlne_(char *cline, int32_t *nchs, slen_t _cline_len);
float     xreal_(char *cline, int32_t *nbeg, int32_t *nlen, int32_t *ierr, slen_t _cline_len);
void      xrealc_(float *xnumb, char *cline, int32_t *nbeg, int32_t *nlen, int32_t *ndec, slen_t _cline_len);
double    xreald_(char *cline, int32_t *nbeg, int32_t *nlen, int32_t *ierr, slen_t _cline_len);
void      ymddat_(int32_t *iyr, int32_t *imon, int32_t *iday, int32_t *istyle, char *cdate, int32_t *ndate, int32_t *ierr, slen_t _cdate_len);
void      zabort_(int32_t *ifltab, int32_t *ierr, char *csub, int32_t *jerr, int32_t *iadd, char *ccomet, slen_t _csub_len, slen_t _ccomet_len);
void      zbdump_(int32_t *ifltab, int32_t *ibgbuf);
void      zbegdt_(int32_t *jul, int32_t *intl, int32_t *iyr, int32_t *imon, int32_t *iday, int32_t *iblock, int32_t *iverno);
void      zcaout_(int32_t *ifltab, int32_t *icunit, int32_t *icdunt, int32_t *lcdcat, int32_t *norecs);
void      zcat_(int32_t *ifltab, int32_t *icunit, int32_t *icdunt, int32_t *inunit, char *cinstr, int32_t *labrev, int32_t *ldosrt, int32_t *lcdcat, int32_t *norecs, slen_t _cinstr_len);
void      zcatdr_(char *cdref, int32_t *ndref, slen_t _cdref_len);
void      zcatfi_(int32_t *ifltab, int32_t *lextnd, int32_t *lselca, int32_t *lcdcat, int32_t *ltonly, int32_t *lerr);
void      zcatit_(int32_t *ifltab, int32_t *iunit, int32_t *lselca, int32_t *lcdcat, char *cinstr, int32_t *lerr, slen_t _cinstr_len);
void      zcatlg_(int32_t *ifltab, int32_t *icunit, int32_t *inunit, char *cinstr, int32_t *ibeg, int32_t *ilen, int32_t *labrev, int32_t *ldosrt, int32_t *norecs, slen_t _cinstr_len);
void      zcheck_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *nhead, int32_t *ndata, int32_t *lfound, slen_t _cpath_len);
void      zchkpn_(char *cpath, int32_t *npath, int32_t *istat, slen_t _cpath_len);
void      zcklnk_(int32_t *ifltab, int32_t *nerror);
void      zckmul_(int32_t *ifltab);
void      zckpat_(int32_t *ifltab, int32_t *nerror);
void      zckpdd_(int32_t *ifltab, int32_t *instr, int32_t *nfixed, int32_t *istat);
void      zckpnb_(int32_t *ifltab, int32_t *nerror);
void      zclose_(int32_t *ifltab);
void      zcofil_(int32_t *iftold, int32_t *iftnew, int32_t *iarray, int32_t *karray, int32_t *ibuff, int32_t *kbuff, int32_t *lrcdel, int32_t *lretag);
void      zcolist_(int32_t *ifltab, int32_t *ifpos, char *cpath, int32_t *npath, int32_t *istat, slen_t _cpath_len);
void      zcorec_(int32_t *iftold, int32_t *iftnew, char *cpold, char *cpnew, int32_t *ibuff1, int32_t *kbuff1, int32_t *ibuff2, int32_t *kbuff2, int32_t *istat, slen_t _cpold_len, slen_t _cpnew_len);
void      zcut_(int32_t *ifltab, char *cpath, int32_t *ldelete, int32_t *ibuffer, int32_t *maxbuff, int32_t *istatus, slen_t _cpath_len);
void      zcutsz_(int32_t *ifltab, char *cpath, int32_t *isize, int32_t *istatus, slen_t _cpath_len);
void      zdblook_(int32_t *ifltab, int32_t *iadd, int32_t *ilen);
void      zdbmod_(int32_t *ifltab, int32_t *iadd, int32_t *ivalue, char *cvalue, int32_t *lusech, slen_t _cvalue_len);
void      zdcinf_(int32_t *jcomp, float *base, int32_t *lbase, int32_t *isize, int32_t *idcpre, int32_t *istat);
void      zdebug1_(int32_t *ival, int64_t *ival8, char *crval, char *cstrng, int32_t *ibytes, slen_t _crval_len, slen_t _cstrng_len);
void      zdebug_(int32_t *munit, int32_t *iarray, int32_t *iadd, int32_t *ilen);
void      zdelet_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *lfound, slen_t _cpath_len);
void      zdswap_(int32_t *iarray, int32_t *nwords);
void      zdtype_(int32_t *ifltab, char *cpath, int32_t *ndata, int32_t *lfound, char *cdtype, int32_t *idtype, slen_t _cpath_len, slen_t _cdtype_len);
void      zerror_(int32_t *ifltab, int32_t *jerr, char *csub, int32_t *istat, int32_t *iadd, char *cstr1, int32_t *nstr1, char *cstr2, int32_t *nstr2, slen_t _csub_len, slen_t _cstr1_len, slen_t _cstr2_len);
void      zfilst_(int32_t *ifltab);
void      zfname_(char *cin, char *cname, int32_t *nname, int32_t *lexist, slen_t _cin_len, slen_t _cname_len);
void      zfpn_(char *ca, int32_t *na, char *cb, int32_t *nb, char *cc, int32_t *nc, char *cd, int32_t *nd, char *ce, int32_t *ne, char *cf, int32_t *nf, char *cpath, int32_t *npath, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len, slen_t _cpath_len);
void      zfsize_(int32_t *ifltab);
void      zfver_(char *cfname, char *cver, int32_t *iver, slen_t _cfname_len, slen_t _cver_len);
void      zgetad_(int32_t *iadd, int32_t *irec, int32_t *iwrd);
void      zgetag_(int32_t *ifltab, char *cpath, char *ctag, slen_t _cpath_len, slen_t _ctag_len);
void      zgetci_(int32_t *ifltab, char *cparti, int32_t *jcomp, float *dbase, int32_t *ldbase, int32_t *ldhigh, int32_t *npre, slen_t _cparti_len);
void      zgetrw_(int32_t *iadd, int32_t *irec, int32_t *iwrd);
void      zgintl_(int32_t *intl, char *chintl, int32_t *nodata, int32_t *istat, slen_t _chintl_len);
void      zgirts_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *ibuff, int32_t *kbuff, int32_t *idum, int32_t *ndum, int32_t *kvals, float *dates, float *values, int32_t *nvals, float *bdate, char *cunits, char *ctype, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zgpnp_(char *cline, char *ca, char *cb, char *cc, char *cd, char *ce, char *cf, int32_t *nparts, slen_t _cline_len, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len);
void      zgtags_(int32_t *ifltab, char *cline, int32_t *istat, slen_t _cline_len);
void      zgtdts_(int32_t *ifltab, char *ca, int32_t *na, char *cb, int32_t *nb, char *cc, int32_t *nc, char *cf, int32_t *nf, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *intl, int32_t *ihead, int32_t *nhead, int32_t *iofset, float *values, int32_t *nvals, char *cunits, char *ctype, int32_t *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cf_len, slen_t _cunits_len, slen_t _ctype_len);
void      zgtpfd_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c2unit, char *c1type, char *c2type, char *clabel, int32_t *klabel, int32_t *nlabel, int32_t *ibuff, int32_t *kbuff, int32_t *nbuff, float *values, int32_t *kvals, int32_t *nvals, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c2unit_len, slen_t _c1type_len, slen_t _c2type_len, slen_t _clabel_len);
void      zgtrec_(int32_t *ifltab, int32_t *iarray, int32_t *narray, int32_t *jadd, int32_t *lsaveb);
void      zhash_(char *cpath, int32_t *npath, int32_t *max, int32_t *ihash, slen_t _cpath_len);
void      zincbk_(int32_t *iblock, int32_t *jul, int32_t *iyr, int32_t *imon, int32_t *iday);
void      zinit_(void);
void      zinqir_(int32_t *ifltab, char *cflg, char *calpha, int32_t *inumb, slen_t _cflg_len, slen_t _calpha_len);
void      zintbk_(float *data, int32_t *nsd, int32_t *ned, int32_t *juls, int32_t *istime, int32_t *intd, int32_t *ndinws, float *wrkspc, int32_t *ndata, int32_t *julswk, int32_t *intlw, float *ofsetw, int32_t *istat, int32_t *iflag);
void      zirbeg_(int32_t *ifltab, int32_t *jul, char *ce, int32_t *iyr, int32_t *imon, int32_t *iday, int32_t *iblock, int32_t *minblk, int32_t *incblk, slen_t _ce_len);
void      zircpy_(int32_t *jarray, int32_t *jtime, float *dvalues, float *svalues, int32_t *jqual, int32_t *ipos, int32_t *ldouble, int32_t *lsqual, int32_t *lrqual, int32_t *lstore, int32_t *ldswap);
void      zirdbl_(int32_t *ifrom, int32_t *ito, int32_t *ltodbl);
void      zirdow_(int32_t *icur, int32_t *npairs, int32_t *ndown, int32_t *imult, int32_t *ibuff);
void      zloadcache_(int32_t *ifltab, int32_t *istat);
void      zmatca_(char *cpath, int32_t *ibpart, int32_t *iepart, int32_t *ilpart, char *ccdate, char *ccprog, int32_t *lmatch, slen_t _cpath_len, slen_t _ccdate_len, slen_t _ccprog_len);
void      zmaxpart_(int32_t *ifltab, int32_t *imxpart);
void      zmin2r_(int32_t *idates, float *dates, float *bdate, int32_t *nvals);
void      zmovbk_(float *svalues, double *dvalues, int32_t *ldouble, int32_t *lfildob, int32_t *jqual, int32_t *lqvals, int32_t *lqblok, int32_t *nstart, int32_t *nvals, int32_t *juls, int32_t *istime, int32_t *intl, float *block, double *dblock, int32_t *iblock, int32_t *ndata, int32_t *julsd, int32_t *istat, int32_t *iflag);
void      zmovwd_(int32_t *ifrom, int32_t *ito, int32_t *number);
void      zmultu_(int32_t *ifltab, int32_t *lock, int32_t *lflush);
void      zndata_(int32_t *ifltab, int32_t *ifpos, int32_t *juls, int32_t *isecs, char *cpath, int32_t *npath, int32_t *juld, int32_t *isecd, int32_t *idtype, int32_t *istat, slen_t _cpath_len);
void      znextts_(int32_t *ifltab, char *cpath, char *cnext, int32_t *lforward, int32_t *istat, slen_t _cpath_len, slen_t _cnext_len);
void      znwbin_(int32_t *ifltab);
void      znwrit_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *nihead, int32_t *nchead, int32_t *nuhead, int32_t *ndata, slen_t _cpath_len);
void      zofset_(int32_t *julian, int32_t *itime, int32_t *interval, int32_t *iflag, int32_t *iofset);
void      zopcat_(char *cdssfi, char *catfil, int32_t *icunit, int32_t *lopen, int32_t *lcatlg, int32_t *lcreat, int32_t *nrec, slen_t _cdssfi_len, slen_t _catfil_len);
void      zopen_(int32_t *ifltab, char *cfname, int32_t *istat, slen_t _cfname_len);
void      zopnca_(char *cdssfi, int32_t *icunit, int32_t *lgenca, int32_t *lopnca, int32_t *lcatca, int32_t *icdunt, int32_t *lgencd, int32_t *lopncd, int32_t *lcatcd, int32_t *nrecs, slen_t _cdssfi_len);
void      zordpn_(int32_t *lselca, int32_t *lerr);
void      zowrit_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *nihead, int32_t *nchead, int32_t *nuhead, int32_t *ndata, slen_t _cpath_len);
void      zpaste_(int32_t *ifltab, int32_t *ibuffer, int32_t *istatus);
void      zpath_(char *ca, char *cb, char *cc, char *cd, char *ce, char *cf, char *cpath, int32_t *npath, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len, slen_t _cpath_len);
void      zpirts_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *ibuff, int32_t *kbuff, int32_t *idum, int32_t *ndum, float *dates, float *values, int32_t *nvals, float *bdate, char *cunits, char *ctype, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zplist_(int32_t *ifltab, char *cinstr, int32_t *ifpos, char *cpath, int32_t *npath, int32_t *istat, slen_t _cinstr_len, slen_t _cpath_len);
void      zprtc_(int32_t *munit, int32_t *ibuff, int32_t *next);
void      zprtci_(int32_t *ifltab, int32_t *lall, char *cparts, slen_t _cparts_len);
void      zptdts_(int32_t *ifltab, char *ca, int32_t *na, char *cb, int32_t *nb, char *cc, int32_t *nc, char *cf, int32_t *nf, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *intl, int32_t *ihead, int32_t *nhead, float *buff, float *values, int32_t *nvals, char *cunits, char *ctype, int32_t *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cf_len, slen_t _cunits_len, slen_t _ctype_len);
void      zptpfd_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c2unit, char *c1type, char *c2type, char *clabel, int32_t *klabel, int32_t *nlabel, int32_t *ibuff, int32_t *kbuff, int32_t *nbuff, float *values, int32_t *kvals, int32_t *nvals, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c2unit_len, slen_t _c1type_len, slen_t _c2type_len, slen_t _clabel_len);
void      zptrec_(int32_t *ifltab, int32_t *iarray, int32_t *narray, int32_t *jadd, int32_t *lsaveb);
void      zquery_(char *cflg, char *calpha, int32_t *inumb, slen_t _cflg_len, slen_t _calpha_len);
void      zr2min_(int32_t *idates, float *dates, int32_t *jdate, int32_t *nvals);
void      zrdbuf_(int32_t *ifltab, char *cpath, int32_t *ihbuff, int32_t *khbuff, int32_t *nhbuff, int32_t *idbuff, int32_t *kdbuff, int32_t *ndbuff, int32_t *lend, int32_t *iplan, int32_t *lfound, slen_t _cpath_len);
void      zrdcat_(int32_t *iunit, int32_t *lall, int32_t *junit, char *ctags, int32_t *ntags, char *cpath, int32_t *npath, int32_t *nfound, slen_t _ctags_len, slen_t _cpath_len);
void      zrdinf_(int32_t *ifltab, char *cpath, int32_t *nhead, int32_t *ndata, int32_t *istat, slen_t _cpath_len);
void      zrdpat_(int32_t *iunit, int32_t *ipos, int32_t *inumb, char *ctag, char *cpath, int32_t *npath, int32_t *lend, slen_t _ctag_len, slen_t _cpath_len);
void      zrdpn_(int32_t *iunit, int32_t *ipos, int32_t *inumb, char *cpath, int32_t *npath, slen_t _cpath_len);
void      zrdprm_(int32_t *ifltab, int32_t *lsave);
void      zread_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *ihead, int32_t *nhead, int32_t *idata, int32_t *ndata, int32_t *iplan, int32_t *lfound, slen_t _cpath_len);
void      zreadx_(int32_t *ifltab, char *cpath, int32_t *iihead, int32_t *kihead, int32_t *nihead, int32_t *ichead, int32_t *kchead, int32_t *nchead, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *idata, int32_t *kdata, int32_t *ndata, int32_t *iplan, int32_t *lfound, slen_t _cpath_len);
void      zrecin_(int32_t *ifltab, int32_t *iout, int32_t *ilevel, char *cpath, int32_t *ibuff, int32_t *kbuff, int32_t *lfound, slen_t _cpath_len);
void      zrecadd_(int32_t *ifltab, const char *ckpath, int64_t *iladd, int32_t *istat, slen_t _cpath_len);
void      zrenam_(int32_t *ifltab, char *cpatho, int32_t *npatho, char *cpathn, int32_t *npathn, int32_t *lfound, slen_t _cpatho_len, slen_t _cpathn_len);
void      zretag_(int32_t *ifltab, char *cpath, int32_t *npath, char *ctag, int32_t *lfound, slen_t _cpath_len, slen_t _ctag_len);
void      zrinfo_(int32_t *ifltab, char *cpath, int32_t *lfound, int32_t *idtype, char *cdtype, int32_t *ldoub, int32_t *lqual, int32_t *iprecis, char *crtag, char *clwdate, char *clwtime, char *cpname, int32_t *ivers, int32_t *ndata, int32_t *nspace, int32_t *icompres, int32_t *lpass, slen_t _cpath_len, slen_t _cdtype_len, slen_t _crtag_len, slen_t _clwdate_len, slen_t _clwtime_len, slen_t _cpname_len);
void      zrits_(int32_t *ifltab, char *cpath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *itimes, float *values, int32_t *kvals, int32_t *nvals, int32_t *ibdate, char *cunits, char *ctype, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zritsc_(int32_t *ifltab, char *cpath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *lgetdob, int32_t *lfildob, int32_t *itimes, float *svalues, double *dvalues, int32_t *kvals, int32_t *nvals, int32_t *ibdate, int32_t *iqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, char *csupp, int32_t *itzone, char *ctzone, double *coords, int32_t *icdesc, int32_t *lcoords, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zritsi_(int32_t *ifltab, char *cpath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *lgetdob, int32_t *lfildob, int32_t *itimes, float *svalues, double *dvalues, int32_t *kvals, int32_t *nvals, int32_t *ibdate, int32_t *iqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, double *coords, int32_t *icdesc, int32_t *lcoords, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zritsx_(int32_t *ifltab, char *cpath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *itimes, float *svalues, int32_t *kvals, int32_t *nvals, int32_t *ibdate, int32_t *iqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zritsxd_(int32_t *ifltab, char *cpath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *itimes, double *dvalues, int32_t *kvals, int32_t *nvals, int32_t *ibdate, int32_t *iqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrmem_(int32_t *iunit, int32_t *irec, int32_t *iarray, int32_t *nwords, int32_t *istat);
void      zrpd_(int32_t *ifltab, char *cpath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, int32_t *kvals, int32_t *nvals, char *clabel, int32_t *klabel, int32_t *label, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zrpdd_(int32_t *ifltab, char *cpath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, double *dvalues, int32_t *kvals, int32_t *nvals, char *clabel, int32_t *klabel, int32_t *label, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zrpdi_(int32_t *ifltab, char *cpath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, double *dvalues, int32_t *ldouble, int32_t *kvals, int32_t *nvals, char *clabel, int32_t *klabel, int32_t *label, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zrrec_(int32_t *iunit, int32_t *irec, int32_t *iarray, int32_t *nwords, int32_t *iswap, int32_t *istat, int32_t *jstat);
void      zrrst_(int32_t *ifltab, char *cpath, int32_t *ietim, char *cloc, char *catim, char *chparm, char *chunit, char *cfparm, char *cfunit, char *ccmt, char *copt, int32_t *lsnum, int32_t *isnum, int32_t *ldatum, float *datum, int32_t *lstage, int32_t *ibhi, int32_t *ibhu, float *huv, int32_t *ibho, float *hov, int32_t *ibfi, int32_t *ibfu, float *fuv, int32_t *ibfo, float *fov, int32_t *kbase, int32_t *nbase, float *height, float *flow, int32_t *kshift, int32_t *nshift, int32_t *isti, int32_t *istu, int32_t *isto, int32_t *isbi, int32_t *isbu, float *sbuv, int32_t *isbo, float *sbov, int32_t *ishi, int32_t *ishu, float *shuv, int32_t *isho, float *shov, int32_t *latmsk, int32_t *jbdate, int32_t *ietime, int32_t *iatime, int32_t *nshftp, int32_t *kshval, int32_t *nshval, float *shifts, int32_t *lcoff, float *cofval, int32_t *koff, int32_t *noff, int32_t *iobi, int32_t *iobu, float *obuv, int32_t *iobo, float *obov, int32_t *iohi, int32_t *iohu, float *ohuv, int32_t *ioho, float *ohov, float *offset, int32_t *ihoriz, int32_t *istat, slen_t _cpath_len, slen_t _cloc_len, slen_t _catim_len, slen_t _chparm_len, slen_t _chunit_len, slen_t _cfparm_len, slen_t _cfunit_len, slen_t _ccmt_len, slen_t _copt_len);
void      zrrsti_(int32_t *ifltab, char *cpath, int32_t *ifcat, int32_t *iintrp, int32_t *iuflow, int32_t *ioflow, int32_t *lfound, int32_t *ktimes, int32_t *ntimes, int32_t *itimes, int32_t *istat, slen_t _cpath_len);
void      zrrtpa_(int32_t *ifltab, char *cpath, float *values, int32_t *nvals, char *cunits, char *ctype, int32_t *iuhead, int32_t *kheadu, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrts_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, float *values, char *cunits, char *ctype, int32_t *iofset, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrtsb_(int32_t *ifltab, int32_t *juls, int32_t *istime, int32_t *intl, int32_t *julsd, int32_t *nstart, int32_t *nldata, int32_t *nadata, int32_t *nvals, int32_t *lgetdob, int32_t *lfildob, float *svalues, double *dvalues, int32_t *jqual, int32_t *lqblok, int32_t *lqual, int32_t *jcomp, int32_t *lfound, int32_t *istat);
void      zrrtsc_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *kvals, int32_t *nvals, int32_t *lgetdob, int32_t *lfildob, float *svalues, double *dvalues, int32_t *jqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, char *csupp, int32_t *iofset, int32_t *jcomp, int32_t *itzone, char *ctzone, double *coords, int32_t *icdesc, int32_t *lcoords, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zrrtsi_(int32_t *ifltab, char *cpath, char *crdate, char *crtime, int32_t *kvals, int32_t *nvals, int32_t *lgetdob, int32_t *lfildob, float *svalues, double *dvalues, int32_t *jqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *iofset, int32_t *jcomp, double *coords, int32_t *icdesc, int32_t *lcoords, int32_t *istat, slen_t _cpath_len, slen_t _crdate_len, slen_t _crtime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrtsx_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, float *svalues, int32_t *jqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *iofset, int32_t *jcomp, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrtsxd_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, double *dvalues, int32_t *jqual, int32_t *lqual, int32_t *lqread, char *cunits, char *ctype, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *iofset, int32_t *jcomp, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrtall_(int32_t *ifltab);
void      zrtext_(int32_t *ifltab, char *cpath, int32_t *iunit, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *lccntl, int32_t *nlines, int32_t *istat, slen_t _cpath_len);
void      zrtxta_(int32_t *ifltab, char *cpath, char *carray, int32_t *karray, int32_t *nlines, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _carray_len);
void      zrtxts_(int32_t *ifltab, char *cpath, char *cstring, int32_t *kstring, int32_t *nstring, int32_t *iuhead, int32_t *kuhead, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _cstring_len);
void      zscomp_(int32_t *icomp, float *base, int32_t *lbase, int32_t *lhigh, int32_t *npre);
void      zselca_(char *cpath, int32_t *npath, char *cctag, char *ccprog, char *ccdate, char *cctime, char *cdtype, int32_t *idtype, int32_t *irvers, int32_t *ndata, int32_t *nhead, int32_t *jnpath, int32_t *lselca, int32_t *lmatch, int32_t *lcdcat, int32_t *lerr, slen_t _cpath_len, slen_t _cctag_len, slen_t _ccprog_len, slen_t _ccdate_len, slen_t _cctime_len, slen_t _cdtype_len);
void      zset_(char *cflg, char *cstr, int32_t *numb, slen_t _cflg_len, slen_t _cstr_len);
void      zsetca_(char *cinstr, int32_t *lselca, slen_t _cinstr_len);
void      zsetci_(int32_t *ifltab, char *cpart, int32_t *lpart, int32_t *jcomp, float *dbase, int32_t *ldbase, int32_t *ldhigh, int32_t *npre, int32_t *istat, slen_t _cpart_len);
void      zsetfi_(int32_t *ifltab, char *cparam, char *calpha, int32_t *inumb, int32_t *istatus, slen_t _cparam_len, slen_t _calpha_len);
void      zsetpr_(int32_t *ifltab, char *cflg, char *cstr, int32_t *inumb, slen_t _cflg_len, slen_t _cstr_len);
void      zsits_(int32_t *ifltab, char *cpath, int32_t *itimes, float *values, int32_t *nvals, int32_t *ibdate, char *cunits, char *ctype, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsitsc_(int32_t *ifltab, char *cpath, int32_t *itimes, float *values, double *dvalues, int32_t *ldouble, int32_t *nvalue, int32_t *ibdate, int32_t *jqual, int32_t *lsqual, char *cunits, char *ctype, double *coords, int32_t *ncoords, int32_t *icdesc, int32_t *ncdesc, char *csupp, int32_t *itzone, char *ctzone, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zsitsi_(int32_t *ifltab, char *cpath, int32_t *itimes, float *svalues, double *dvalues, int32_t *ldouble, int32_t *nvalue, int32_t *ibdate, int32_t *jqual, int32_t *lsqual, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, double *coords, int32_t *ncoords, int32_t *icdesc, int32_t *ncdesc, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsitsx_(int32_t *ifltab, char *cpath, int32_t *itimes, float *values, int32_t *nvalue, int32_t *ibdate, int32_t *jqual, int32_t *lsqual, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsitsxd_(int32_t *ifltab, char *cpath, int32_t *itimes, double *dvalues, int32_t *nvalue, int32_t *ibdate, int32_t *jqual, int32_t *lsqual, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, int32_t *inflag, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zspd_(int32_t *ifltab, char *cpath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, char *clabel, int32_t *label, int32_t *iuhead, int32_t *nuhead, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zspdd_(int32_t *ifltab, char *cpath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, double *dvalues, char *clabel, int32_t *label, int32_t *iuhead, int32_t *nuhead, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zspdi_(int32_t *ifltab, char *cpath, int32_t *nord, int32_t *ncurve, int32_t *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, double *dvalues, int32_t *ldouble, char *clabel, int32_t *label, int32_t *iuhead, int32_t *nuhead, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zsqprm_(int32_t *iftold, int32_t *iftnew, int32_t *lretag);
void      zsrst_(int32_t *ifltab, char *cpath, char *cloc, char *catim, char *chparm, char *chunit, char *cfparm, char *cfunit, char *ccmt, char *copt, int32_t *lsnum, int32_t *isnum, int32_t *ldatum, float *datum, int32_t *lstage, int32_t *ibhi, int32_t *ibhu, float *huv, int32_t *ibho, float *hov, int32_t *ibfi, int32_t *ibfu, float *fuv, int32_t *ibfo, float *fov, int32_t *nbase, float *height, float *flow, int32_t *nshift, int32_t *isti, int32_t *istu, int32_t *isto, int32_t *isbi, int32_t *isbu, float *sbuv, int32_t *isbo, float *sbov, int32_t *ishi, int32_t *ishu, float *shuv, int32_t *isho, float *shov, int32_t *latmsk, int32_t *jbdate, int32_t *ietime, int32_t *iatime, int32_t *nshftp, float *shifts, int32_t *lcoff, float *cofval, int32_t *noff, int32_t *iobi, int32_t *iobu, float *obuv, int32_t *iobo, float *obov, int32_t *iohi, int32_t *iohu, float *ohuv, int32_t *ioho, float *ohov, float *offset, int32_t *ihoriz, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _cloc_len, slen_t _catim_len, slen_t _chparm_len, slen_t _chunit_len, slen_t _cfparm_len, slen_t _cfunit_len, slen_t _ccmt_len, slen_t _copt_len);
void      zsrsti_(int32_t *ifltab, char *cpath, int32_t *iintrp, int32_t *iuflow, int32_t *ioflow, int32_t *iplan, int32_t *istat, slen_t _cpath_len);
void      zsrtpa_(int32_t *ifltab, char *cpath, float *values, int32_t *nvals, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrts_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, float *values, char *cunits, char *ctype, int32_t *iplan, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrtsc_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, int32_t *ldouble, float *values, double *dvalues, int32_t *jqual, int32_t *lqual, char *cunits, char *ctype, double *coords, int32_t *ncoords, int32_t *icdesc, int32_t *ncdesc, char *csupp, int32_t *itzone, char *ctzone, int32_t *iplan, int32_t *jcomp, float *basev, int32_t *lbasev, int32_t *ldhigh, int32_t *nprec, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zsrtsi_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, int32_t *ldouble, float *svalues, double *dvalues, int32_t *jqual, int32_t *lqual, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, double *coords, int32_t *ncoords, int32_t *icdesc, int32_t *ncdesc, int32_t *iplan, int32_t *jcomp, float *basev, int32_t *lbasev, int32_t *ldhigh, int32_t *nprec, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrtsx_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, float *values, int32_t *jqual, int32_t *lqual, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, int32_t *iplan, int32_t *jcomp, float *basev, int32_t *lbasev, int32_t *ldhigh, int32_t *nprec, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrtsxd_(int32_t *ifltab, char *cpath, char *cdate, char *ctime, int32_t *nvals, double *dvalues, int32_t *jqual, int32_t *lqual, char *cunits, char *ctype, int32_t *iuhead, int32_t *nuhead, int32_t *iplan, int32_t *jcomp, float *basev, int32_t *lbasev, int32_t *ldhigh, int32_t *nprec, int32_t *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zstags_(int32_t *ifltab, char *cline, int32_t *istat, slen_t _cline_len);
void      zstext_(int32_t *ifltab, char *cpath, int32_t *iunit, int32_t *iuhead, int32_t *nuhead, int32_t *nlines, int32_t *istat, slen_t _cpath_len);
void      zstfh_(char *clabel, char *citem, int32_t *nitem, int32_t *ihead, int32_t *khead, int32_t *nhead, int32_t *ierr, slen_t _clabel_len, slen_t _citem_len);
void      zstxta_(int32_t *ifltab, char *cpath, char *carray, int32_t *narray, int32_t *iuhead, int32_t *nuhead, int32_t *istat, slen_t _cpath_len, slen_t _carray_len);
void      zswap_(int32_t *in, int32_t *iout);
void      zswapw_(int32_t *idata, int32_t *ndata);
void      ztagfi_(int32_t *ifltab, int32_t *ifun, int32_t *nrecs, int32_t *itag, int32_t *jhash);
void      ztagpa_(int32_t *ifltab, int32_t *junit, char *ctags, int32_t *ntags, char *cpath, int32_t *npath, int32_t *nfound, slen_t _ctags_len, slen_t _cpath_len);
void      ztsends_(int32_t *ifltab, char *cpath, int32_t *isearch, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, int32_t *lfound, slen_t _cpath_len);
void      ztsinfo_(int32_t *ifltab, char *cpath, int32_t *juls, int32_t *istime, int32_t *jule, int32_t *ietime, char *cunits, char *ctype, int32_t *lqual, int32_t *ldouble, int32_t *lfound, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      ztsint_(int32_t *ifltab, char *ca, int32_t *na, char *cb, int32_t *nb, char *cc, int32_t *nc, char *cf, int32_t *nf, int32_t *julis, int32_t *isitim, int32_t *jule, int32_t *ietime, int32_t *intin, int32_t *intout, int32_t *ihead, int32_t *nh, float *wrkspc, float *values, int32_t *nvals, char *cunits, char *ctype, int32_t *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cf_len, slen_t _cunits_len, slen_t _ctype_len);
void      ztsrange_(int32_t *ifltab, char *cpath, int32_t *isearch, char *cfirstp, char *clastp, int32_t *nfound, slen_t _cpath_len, slen_t _cfirstp_len, slen_t _clastp_len);
void      ztssrch_(int32_t *ifltab, char *cinpath, int32_t *iunit, char *coutpath, int32_t *nfound, slen_t _cinpath_len, slen_t _coutpath_len);
int       ztstqp_(int32_t *qualwd);
void      zudall_(int32_t *ifltab, int32_t *junit);
void      zudava_(int32_t *ifltab, char *cpath, int32_t *istatus, slen_t _cpath_len);
void      zufpn_(char *ca, int32_t *na, char *cb, int32_t *nb, char *cc, int32_t *nc, char *cd, int32_t *nd, char *ce, int32_t *ne, char *cf, int32_t *nf, char *cpath, int32_t *npath, int32_t *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len, slen_t _cpath_len);
void      zundel_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *istat, slen_t _cpath_len);
void      zupath_(char *cpath, int32_t *ibpart, int32_t *iepart, int32_t *ilpart, int32_t *istat, slen_t _cpath_len);
void      zuprts_(int32_t *ifltab, int32_t *juls, int32_t *istime, int32_t *intl, int32_t *julsd, int32_t *nstart, int32_t *ndata, int32_t *nvals, float *values, int32_t *jqual, int32_t *lqual, int32_t *iplan, int32_t *lerr);
void      zustfh_(char *clabel, char *citem, int32_t *nitem, int32_t *ipos, int32_t *ihead, int32_t *nhead, int32_t *ierr, slen_t _clabel_len, slen_t _citem_len);
void      zwlock_(int32_t *ifltab, char *cact, int32_t *istat, slen_t _cact_len);
void      zwmem_(int32_t *iunit, int32_t *irec, int32_t *iarray, int32_t *nwords, int32_t *istat);
void      zwrbuf_(int32_t *ifltab, char *cpath, int32_t *ihead, int32_t *nhead, int32_t *nthead, int32_t *idata, int32_t *ndata, int32_t *ntdata, int32_t *lend, slen_t _cpath_len);
void      zwrec_(int32_t *iunit, int32_t *irec, int32_t *iarray, int32_t *nwords, int32_t *iswap, int32_t *istat, int32_t *jstat);
void      zwrite_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *iuhead, int32_t *nuhead, int32_t *idata, int32_t *ndata, int32_t *iplan, int32_t *lfound, slen_t _cpath_len);
void      zwritx_(int32_t *ifltab, char *cpath, int32_t *npath, int32_t *iihead, int32_t *nihead, int32_t *ichead, int32_t *nchead, int32_t *iuhead, int32_t *nuhead, int32_t *idata, int32_t *ndata, int32_t *jtype, int32_t *iplan, int32_t *istat, int32_t *lfound, slen_t _cpath_len);

/*------------------------*/
/* Non-supported routines */
/*------------------------*/
#ifdef UNSUPPORTED
void      etime_(void);
void      scnpuf_(char *m, char *csname, int32_t *if34, int32_t *irecsc, int32_t *ncol, int32_t *nrows, int32_t *irow, int32_t *icol, int32_t *istat, slen_t _m_len, slen_t _csname_len);
#endif

/*----------------*/
/* C/C++ Routines */
/*----------------*/
void      chmodf_(char *path, int32_t *mode, int32_t *istat, int32_t l_path);
void      closf_(int32_t *ihandle, int32_t *istat);
void      fildat_(char *cname, char *cfdate, char *cftime, int32_t *istat, int32_t l_cname, int32_t l_cfdate, int32_t l_cftime);
void      filen64_(char *cmask, int32_t *ifatt, char *cmode, char *cfname, int64_t *ifsize, char *cfdate, char *cftime, int32_t *iatt, int32_t *istat, int32_t l_cmask, int32_t l_cmode, int32_t l_cfname, int32_t l_cfdate, int32_t l_cftime);
void      filen_(char *cmask, int32_t *ifatt, char *cmode, char *cfname, int32_t *ifsize, char *cfdate, char *cftime, int32_t *iatt, int32_t *istat, int32_t l_cmask, int32_t l_cmode, int32_t l_cfname, int32_t l_cfdate, int32_t l_cftime);
void      filesize64_(int32_t *handle, int64_t *nbytes);
void      filesize_(int32_t *handle, int32_t *nbytes);
void      filesizen64_(char *filename, int64_t *nbytes, int32_t *status, int32_t filename_len);
void      filesizen_(char *filename, int32_t *nbytes, int32_t *status, int32_t filename_len);
void      filesort_(char *inname, char *outname, int32_t *maxlinewidth, int32_t *maxlines, int32_t *status, int32_t inname_len, int32_t outname_len);
void      flushf_(int32_t *ihandle, int32_t *istat);
unsigned char *getHeclibBuildInfo();
void      getpid_(int32_t *pid);
void      getprocid_(int32_t *pid);
void      gtenv_(char *cname, char *cenv, int32_t *nenv, int32_t *istat, int32_t lcname, int32_t lcenv);
void      ioread_(int32_t *iport, char *carray, int32_t *maxary, int32_t *narray);
void      iowrite_(int32_t *iport, char *carray, int32_t *narray, int32_t *ierr, int32_t lcarray);
void      isonlocaldrive_(char *pathname, int32_t *islocal, int32_t len_pathname);
int       isUndefinedDbl(double value);
int       isundefineddbl_(double *value);
int       isUndefinedFlt(float value);
int       isundefinedflt_(float value);
int       isUndefinedInt(int32_t value);
int       isundefinedint_(int32_t value);
int       isUndefinedShrt(short value);
int       isundefinedshrt_(short value);
void      lockdss64_(int32_t *ihandle, int32_t *mode, int64_t *position, int64_t *nbytes, int32_t *istat);
void      lockdss_(int32_t *ihandle, int32_t *mode, int32_t *position, int32_t *nbytes, int32_t *istat);
void      lockf_(int32_t *ihandle, int32_t *lock, int32_t *istat);
void      lockfr_(int32_t *handle, int32_t *istat);
void      lockfu_(int32_t *handle, int32_t *istat);
void      lockfw_(int32_t *handle, int32_t *istat);
int       lockFile(int32_t ihandle, int32_t mode, int32_t position, int32_t nbytes);
int       lockFile64(int32_t ihandle, int32_t mode, int64_t position, int64_t nbytes);
void      openf_(char *cname, int32_t *iaccess, int32_t *ihandle, int32_t *istat, int32_t len_cname);
void      permissions_(char *path, int32_t *mode, int32_t *istat, int32_t l_path);
void      readf_(int32_t *ihandl, void *buff, int32_t *nbytes, int32_t *istat, int32_t *ntrans);
void      readmem_(int32_t *mbuff, int32_t *wordpos, int32_t *intbuff, int32_t *nwords);
void      reallocatemem_(int32_t **buff, int32_t *nbytes);
void      scncols_(int32_t *columns);
void      scnlines_(int32_t *lines);
void      scnsize_(int32_t *lines, int32_t *columns);
void      seekf64_(int32_t *ihandl, int32_t *iorigin, int64_t *iofset, int64_t *ipos, int32_t *istat);
void      seekf_(int32_t *ihandl, int32_t *iorigin, int32_t *iofset, int32_t *ipos, int32_t *istat);
void      systim_(int32_t *julian, int32_t *sec);
double    undefinedDbl();
double    undefineddbl_();
double    undefinedFlt();
double    undefinedflt_();
double    undefinedInt();
double    undefinedint_();
double    undefinedShrt();
double    undefinedshrt_();
void      waits_(float *secs);
void      writemem_(int32_t *mbuff, int32_t *wordpos, int32_t *intbuff, int32_t *nwords);
void      writf_(int32_t *ihandle, void *buff, int32_t *nbytes, int32_t *istat, int32_t *ntrans);

/*--------------------------*/
/* Unix-only C/C++ Routines */
/*--------------------------*/
#if !defined(_MSC_VER) && !defined(SWIGWIN)
void      getppid_(int32_t *ppid);
void      iosave_(int32_t *iunit, char *cset, int32_t *istat, int32_t l_cset);
void      ioset_(int32_t *iunit, int32_t *iwait, int32_t *nchar, int32_t *istat);
#endif

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* __HECLIB_INCLUDED__ */

