        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:29 2020
        MODULE ADDIAJA_CLN__genmod
          INTERFACE 
            SUBROUTINE ADDIAJA_CLN(SMAT)
              USE SPARSEMODULE
              TYPE (SPARSEMATRIX), INTENT(INOUT) :: SMAT
            END SUBROUTINE ADDIAJA_CLN
          END INTERFACE 
        END MODULE ADDIAJA_CLN__genmod
