        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:29 2020
        MODULE CLN2BAS1AR__genmod
          INTERFACE 
            SUBROUTINE CLN2BAS1AR
            END SUBROUTINE CLN2BAS1AR
          END INTERFACE 
        END MODULE CLN2BAS1AR__genmod
