        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:28 2020
        MODULE FILLGFS__genmod
          INTERFACE 
            SUBROUTINE FILLGFS(IOUT)
              INTEGER(KIND=4) :: IOUT
            END SUBROUTINE FILLGFS
          END INTERFACE 
        END MODULE FILLGFS__genmod
