        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:29:20 2020
        MODULE FILLJA_GNCB__genmod
          INTERFACE 
            SUBROUTINE FILLJA_GNCB(IGFOUNDB,NGNCB,GNCB,MXADJB,MXGNCB)
              INTEGER(KIND=4) :: MXGNCB
              INTEGER(KIND=4) :: MXADJB
              INTEGER(KIND=4) :: NGNCB
              INTEGER(KIND=4) :: IGFOUNDB(NGNCB,MXADJB)
              REAL(KIND=4) :: GNCB(4+2*MXADJB,MXGNCB)
            END SUBROUTINE FILLJA_GNCB
          END INTERFACE 
        END MODULE FILLJA_GNCB__genmod
