        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:32 2020
        MODULE GET_MODFLOW_ARRLENS__genmod
          INTERFACE 
            SUBROUTINE GET_MODFLOW_ARRLENS(SNLAY,SNROW,SNCOL,SNODES)
              INTEGER(KIND=4), INTENT(OUT) :: SNLAY
              INTEGER(KIND=4), INTENT(OUT) :: SNROW
              INTEGER(KIND=4), INTENT(OUT) :: SNCOL
              INTEGER(KIND=4), INTENT(OUT) :: SNODES
            END SUBROUTINE GET_MODFLOW_ARRLENS
          END INTERFACE 
        END MODULE GET_MODFLOW_ARRLENS__genmod
