        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:24 2020
        MODULE GLO2SGBU1FM__genmod
          INTERFACE 
            SUBROUTINE GLO2SGBU1FM
            END SUBROUTINE GLO2SGBU1FM
          END INTERFACE 
        END MODULE GLO2SGBU1FM__genmod
