        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 06 10:28:18 2020
        MODULE GNCN2DISU1N4__genmod
          INTERFACE 
            SUBROUTINE GNCN2DISU1N4
            END SUBROUTINE GNCN2DISU1N4
          END INTERFACE 
        END MODULE GNCN2DISU1N4__genmod
